#!/usr/bin/env python3
import argparse,json,sqlite3
from pathlib import Path
def audit(path):
 c=sqlite3.connect('file:'+Path(path).resolve().as_posix()+'?mode=ro',uri=True);c.row_factory=sqlite3.Row;c.execute('pragma query_only=on');checks=[]
 def add(name,value,expected=0):checks.append({'check':name,'value':value,'expected':expected,'status':'PASS' if value==expected else 'FAIL'})
 add('integrity',c.execute('pragma integrity_check').fetchone()[0],'ok');add('foreign_key_check',len(c.execute('pragma foreign_key_check').fetchall()))
 for t,k in [('UserSynthetic','user_id'),('SessionSynthetic','session_id'),('Search','search_id'),('SearchFilter','search_filter_id'),('SearchResult','search_result_id'),('ActionEvent','event_id'),('SearchTransition','transition_id')]:add(f'{t}_pk',c.execute(f'select count(*)-count(distinct {k})+sum({k} is null) from {t}').fetchone()[0])
 add('search_filter_1to1',c.execute('select count(*) from Search s left join SearchFilter f using(search_id) where f.search_id is null').fetchone()[0]+c.execute('select count(*) from(select search_id,count(*)n from SearchFilter group by search_id having n<>1)').fetchone()[0])
 add('result_count',c.execute('select count(*) from Search s left join(select search_id,count(*)n from SearchResult group by search_id)r using(search_id) where total_result_count<>coalesce(n,0)').fetchone()[0]);add('duplicate_hotel',c.execute('select count(*) from(select search_id,hotel_id,count(*)n from SearchResult group by search_id,hotel_id having n>1)').fetchone()[0]);add('event_before_search',c.execute('select count(*) from ActionEvent e join Search s using(search_id) where e.event_at<s.search_time').fetchone()[0]);add('event_after_session',c.execute('select count(*) from ActionEvent e join SessionSynthetic s using(session_id) where e.event_at>s.ended_at').fetchone()[0]);add('time_inversion',c.execute('with x as(select session_id,search_time,lag(search_time)over(partition by session_id order by search_sequence)p from Search)select count(*) from x where search_time<p').fetchone()[0]);add('booking',c.execute('select count(*) from Booking').fetchone()[0])
 users=c.execute('select count(*) from UserSynthetic').fetchone()[0];arms={r[0]:r[1] for r in c.execute('select sample_set_type,count(*) from UserSynthetic group by 1')};pairs=c.execute('select count(*) from(select pair_id,count(*)n,count(distinct sample_set_type)a from UserSynthetic group by pair_id having n=2 and a=2)').fetchone()[0];add('arm_balance',abs(arms.get('control',0)-arms.get('treatment',0)));add('pair_completeness',users//2-pairs)
 total=c.execute('select count(*) from Search').fetchone()[0];zero=c.execute('select count(*) from Search where total_result_count=0').fetchone()[0];follow=c.execute('with x as(select total_result_count,lead(total_result_count)over(partition by session_id order by search_sequence)n from Search)select sum(total_result_count=0 and n is not null),sum(total_result_count=0 and n>0)from x').fetchone();final=c.execute('with x as(select session_id,total_result_count,row_number()over(partition by session_id order by search_sequence desc)rn,max(total_result_count=0)over(partition by session_id)z from Search)select sum(rn=1 and z=1 and total_result_count>0),sum(rn=1 and z=1)from x').fetchone();pos=total-zero;hs=c.execute("select count(distinct s.search_id) from Search s join SearchResult r on r.search_id=s.search_id and r.result_rank=1 join ActionEvent e on e.search_id=s.search_id and e.hotel_id=r.hotel_id and e.event_type='hotel_detail_view' where s.total_result_count>0").fetchone()[0];he=c.execute("select count(*) from Search s join SearchResult r on r.search_id=s.search_id and r.result_rank=1 join ActionEvent e on e.search_id=s.search_id and e.hotel_id=r.hotel_id and e.event_type='hotel_detail_view'").fetchone()[0]
 metrics={'users':users,'arms':arms,'pairs':pairs,'search_zero':[zero,total],'zero_followup':[follow[0],zero],'immediate_recovery':[follow[1],follow[0]],'final_recovery':[final[0],final[1]],'card_h_search':[hs,pos],'card_h_event':he,'sg3':c.execute("select count(*) from SessionSynthetic where outcome_segment='SG3'").fetchone()[0],'sg4':c.execute("select count(*) from SessionSynthetic where outcome_segment='SG4'").fetchone()[0]};c.close();return {'checks':checks,'metrics':metrics,'pass':all(x['status']=='PASS' for x in checks)}
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('db');p.add_argument('--json');a=p.parse_args();r=audit(a.db);s=json.dumps(r,indent=2);print(s);Path(a.json).write_text(s,encoding='utf-8') if a.json else None
