from html import escape
import json, math

def render_overview(root):
    d=json.loads((root/'data/overview_10000.json').read_text());c=d['counts'];period=d['start'][:10]+' ~ '+d['end'][:10]+' (UTC)'
    def panel(title,rows,unit='명',mode='bar',basis='',percent=False,id=''):
        # Each row is (category, numeric value, exact denominator/context label).
        W=max(800,len(rows)*115) if mode=='bar' else 1100;H=400;left=65;right=W-30;top=50;bottom=290
        peak=max([r[1] for r in rows]+[1]);maximum=100 if percent else max(1,math.ceil(peak/4))*4
        if not percent and maximum>100: maximum=math.ceil(maximum/100)*100
        svg=[]
        for j in range(5):
            y=bottom-(bottom-top)*j/4;value=maximum*j/4
            svg.append(f'<line x1="{left}" x2="{right}" y1="{y}" y2="{y}" stroke="#e3e9ef"/><text x="{left-10}" y="{y+4}" text-anchor="end" fill="#68788a" font-size="12">{value:,.0f}{unit}</text>')
        points=[]
        for i,(label,value,note) in enumerate(rows):
            x=left+(right-left)*(i+.5)/len(rows);y=bottom-(bottom-top)*value/maximum;points.append((x,y))
            text=f'{value:,.2f}{unit}' if unit in ['%','회'] else f'{value:,.0f}{unit}'
            if mode=='bar':
                bw=min(85,(right-left)/len(rows)*.52)
                svg.append(f'<rect x="{x-bw/2}" y="{y}" width="{bw}" height="{bottom-y}" fill="{["#4569df","#219a87","#b4864b","#91a5c3"][i%4]}" rx="5"><title>{escape(label+": "+text+" · "+note)}</title></rect>')
            else:svg.append(f'<circle cx="{x}" cy="{y}" r="5" fill="#4569df"><title>{escape(label+": "+text+" · "+note)}</title></circle>')
            show=mode=='bar' or len(rows)<=12 or i%max(1,math.ceil(len(rows)/10))==0 or i==len(rows)-1
            if show:
                svg.append(f'<text x="{x}" y="{max(20,y-13)}" text-anchor="middle" fill="#20324b" font-size="14" font-weight="700">{text}</text><text x="{x}" y="318" text-anchor="middle" fill="#20324b" font-size="12">{escape(label)}</text>')
                if mode=='bar':svg.append(f'<text x="{x}" y="344" text-anchor="middle" fill="#68788a" font-size="11">{escape(note)}</text>')
        if mode=='line':svg.insert(5,'<polyline points="'+' '.join(f'{x},{y}' for x,y in points)+'" fill="none" stroke="#4569df" stroke-width="3"/>')
        aria=escape(title+'; '+'; '.join(f'{a} {b:.2f}{unit}' for a,b,n in rows))
        return f'<article class="analytics-chart overview-chart"'+(f' id="{id}"' if id else '')+'><div class="analytics-chart-head"><div><span class="analytics-kicker">전체 검색 경험 · 합성 10,000명</span><h3>'+title+'</h3></div></div><div class="analytics-meta"><span>기간: '+period+'</span><span>대상: 전체 검색 참여 사용자</span><span>기준: '+basis+'</span></div><div class="analytics-plot"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+str(W)+' '+str(H)+'" role="img" aria-label="'+aria+'">'+''.join(svg)+'</svg></div><p class="analytics-foot">합성 시간축·행동 분포입니다. 실제 방문 추이·계절성·실사용자의 행동 효과로 해석하지 않습니다. 시간별 추이의 마지막 날은 일부 시간만 포함합니다. '+('점에 마우스를 올리면 상세 수치를 확인할 수 있습니다.' if mode=='line' else '막대 위 값, 아래 구성비 또는 분모를 함께 확인하세요.')+'</p></article>'
    def table(rows):return '<div class="scroll"><table><thead><tr><th>사용자 조건</th><th>사용자 · 구성비</th><th>총 검색</th><th>평균 검색</th><th>0건 검색률</th><th>0건 경험 사용자</th></tr></thead><tbody>'+''.join(f'<tr><td>{escape(x["label"])}</td><td>{x["users"]:,}명 · {x["share"]:.2f}%</td><td>{x["searches"]:,}건</td><td>{x["avg"]:.2f}회</td><td>{x["zero"]:,}/{x["searches"]:,} · {x["zero_rate"]:.2f}%</td><td>{x["zero_users"]:,}명</td></tr>' for x in rows)+'</tbody></table></div>'
    cards=[('검색 참여 사용자',f'{c["users"]:,}','명','검색 기록이 있는 고유 사용자'),('검색 세션',f'{c["sessions"]:,}','개','현재 생성 구조: 사용자당 1세션'),('전체 검색 요청',f'{c["searches"]:,}','건','반복 검색을 포함한 전체 요청'),('사용자당 검색',f'{c["searches"]/c["users"]:.2f}','회','전체 검색 ÷ 검색 참여 사용자')]
    head='<section id="overview-top"><span class="label">01 · 참여와 검색 경험</span><h1>얼마나 검색하고,<br>어떤 검색 경험을 했을까?</h1><p class="lead">검색 참여 규모에서 시작해 검색량의 흐름, 사용자의 초기 조건, 결과를 찾기까지의 경험을 살펴봅니다.</p><div class="overview-scope"><span>합성 10,000명 · 전체 사용자 합산</span><span>검색 시간축 '+period+'</span><span>최신 합성 DB 직접 집계 · 탐색용 / HOLD</span></div><div class="report-metrics">'+''.join(f'<article class="report-metric"><h3>{a}</h3><strong>{b}<small>{u}</small></strong><p>{n}</p></article>' for a,b,u,n in cards)+'</div><p class="meta">진입은 <b>검색 참여·세션 시작</b> 기준입니다. 광고·추천·직접 방문 등 유입 채널과 검색하지 않은 방문자는 이 데이터에서 확인할 수 없습니다.</p></section>'
    trend=d['trend'];short=lambda s:s[5:] if len(s)>7 else s
    trends='<section id="overview-trends"><h2 class="overview-section-title">01 · 언제 들어와 얼마나 검색했나</h2><p class="overview-partial">합성 시간축 · 마지막 날은 '+d['end'][11:19]+' UTC까지만 포함합니다. 마지막 구간의 감소를 실제 이용 감소로 해석하지 않습니다.</p>'+panel(d['grain']+'별 검색량',[(short(x['label']),x['searches'],f'결과 없음 {x["zero"]:,}건') for x in trend],unit='건',mode='line',basis='각 기간에 발생한 전체 검색 건수')+panel(d['grain']+'별 검색 참여 사용자',[(short(x['label']),x['users'],f'시작 세션 {x["entries"]:,}개') for x in trend],mode='line',basis='기간 내 검색한 고유 사용자 · 기간 간 중복 가능')+panel(d['grain']+'별 시작 세션',[(short(x['label']),x['entries'],'새로 시작된 검색 세션') for x in trend],unit='개',mode='line',basis='기간 내 started_at 기준 세션 시작 · 방문 유입과 다름')+'</section>'
    names={'0':'미설정','1':'설정'};region={'coastal':'해안','inland':'내륙','island':'도서','metro':'도시'}
    composition='<section id="overview-users"><h2 class="overview-section-title">02 · 어떤 조건의 사용자가 검색했나</h2><p class="lead">처음 주어진 가격·옵션·지역 조건입니다. 6개 검색의도군의 변경 의향을 뜻하지 않습니다.</p>'
    for dim,title,mapping in [('price','초기 가격 조건',names),('opt','초기 옵션 수',{})]:
        rows=[{**x,'label':mapping.get(x['label'],x['label'])} for x in d['profiles'][dim]]
        composition+=panel(title+'별 사용자 구성',[(x['label'],x['users'],f'{x["share"]:.2f}% / 10,000명') for x in rows],basis='각 초기 조건군 사용자 ÷ 전체 10,000명')
        composition+='<details><summary>'+title+'별 검색량·검색 경험 비교</summary>'+table(rows)+'</details>'
    composition+='</section>'
    ordered=['첫 결과 있음·클릭','첫 결과 있음·미클릭','처음 0건·이후 회복','처음 0건·끝까지 미회복'];exp=sorted(d['experience'],key=lambda x:ordered.index(x['label']))
    experience='<section id="overview-experience"><h2 class="overview-section-title">03 · 어떤 검색 경험으로 이어졌나</h2>'+panel('첫 검색부터 세션 종료까지 · 검색 경험 4가지',[(x['label'],x['users'],f'{x["share"]:.2f}% / 10,000명') for x in exp],basis='첫 검색 결과·세션 내 클릭·후속 결과로 분류 · 중복 없는 4개 군')+'<p class="meta">첫 결과 있음·클릭은 같은 세션에 클릭이 1회 이상 있다는 뜻입니다. 처음부터 클릭했거나 예약했다는 뜻은 아닙니다. 처음 0건·이후 회복은 이후 한 번이라도 결과가 나온 경우입니다.</p>'+panel('검색 경험별 사용자당 검색 횟수',[(x['label'],x['avg'],f'{x["searches"]:,}검색 / {x["users"]:,}명') for x in exp],unit='회',basis='경험군의 전체 검색 ÷ 경험군 사용자')+'<details><summary>경험군별 상세 수치와 분모</summary>'+table(exp)+'</details></section>'
    search_experience='<section id="overview-results"><h2 class="overview-section-title">04 · 검색 결과 없음은 얼마나 겪었나</h2><div class="analytics-grid">'+panel('검색 요청의 결과 분포',[('결과 있음',c['searches']-c['zero'],f'{(1-c["zero"]/c["searches"])*100:.2f}%'),('결과 없음',c['zero'],f'{c["zero"]/c["searches"]*100:.2f}%')],unit='건',basis='전체 65,355검색')+panel('0건 경험 여부 · 사용자 기준',[('0건 미경험',c['users']-c['zero_users'],f'{(1-c["zero_users"]/c["users"])*100:.2f}%'),('0건 경험',c['zero_users'],f'{c["zero_users"]/c["users"]*100:.2f}%')],basis='전체 10,000명 · 세션 안에서 한 번이라도 0건')+'</div>'+panel('실제 검색 조건별 결과 없음 비율',[(x['label'],x['zero_rate'],f'{x["zero"]:,} / {x["searches"]:,}검색') for x in d['filters']],unit='%',basis='해당 검색 조건의 0건 검색 ÷ 해당 조건의 전체 검색',percent=True)+'</section>'
    seq=panel('몇 번째 검색까지 이어졌나',[(x['label']+'회',x['users'],f'{x["users"]/c["users"]*100:.2f}% / 전체 사용자') for x in d['sequence']],mode='line',basis='해당 순번의 검색이 존재하는 사용자 · 최대 31회 생성 제한',id='overview-depth')
    foot='<details><summary>출처·집계 정의·이전 자료와의 연결</summary><p>기존 1,000명 대시보드의 검색량·조건·검색 후 경험 비교 구조를 참고하고, 최신 10,000명 SQLite 전체를 다시 집계했습니다. 합성 현황은 10,000명 기준이며, 일본 도시 영역만 별도 표시한 원본 296검색 기준입니다. 이전 집계와 정의가 달라질 수 있어 숫자를 합산하지 않습니다.</p><p>기준 DB: '+escape(d['source'])+'</p><p class="mono">SHA-256 '+d['sha256']+'</p><p>의도군·연령·유입 채널은 데이터에 없어 추정하지 않았습니다. 합성 전체의 현황이므로 실제 모집단 구성과 다릅니다. 세션 시작과 검색 참여를 실제 방문 전환 퍼널로 해석하지 않습니다.</p></details>'
    colors=['#4569df','#219a87','#b4864b','#8a6bc1','#91a5c3'];arcs=[];legend=[];offset=0
    for i,x in enumerate(d['keywords']):
        share=x['n']/c['users']*100;color=colors[i%len(colors)]
        arcs.append(f'<circle cx="180" cy="180" r="118" pathLength="100" fill="none" stroke="{color}" stroke-width="48" stroke-dasharray="{share} {100-share}" stroke-dashoffset="{-offset}" transform="rotate(-90 180 180)"><title>{escape(x["label"])} · {x["n"]:,}명 · {share:.2f}%</title></circle>')
        legend.append(f'<li><span class="keyword-dot" style="background:{color}"></span><strong>{escape(x["label"])}</strong><span>{x["n"]:,}명</span><b>{share:.2f}%</b></li>');offset+=share
    keywords='<section class="analytics-chart" id="overview-keywords"><div class="analytics-chart-head"><div><span class="analytics-kicker">첫 검색 · 검색어 구성</span><h3>어떤 검색어로 검색을 시작했나?</h3></div></div><div class="analytics-meta"><span>기간: '+period+'</span><span>대상: 첫 검색 10,000건 · 사용자별 1건</span><span>분모: 전체 검색 참여 10,000명</span></div><div class="keyword-layout"><svg viewBox="0 0 360 360" role="img" aria-label="첫 입력 검색어 비중: business 20.46%, hotel 20.38%, family 20.20%, stay 20.04%, weekend 18.92%">'+''.join(arcs)+'<text x="180" y="178" text-anchor="middle" class="donut-total">10,000</text><text x="180" y="207" text-anchor="middle" class="donut-sub">첫 검색 · 명</text></svg><ul class="keyword-legend">'+''.join(legend)+'</ul></div><p class="meta">외부 검색엔진 유입어가 아닌 <b>사이트 내 첫 입력 검색어</b>입니다. 이 다섯 단어는 합성 생성값이며 실제 유입 키워드 순위를 뜻하지 않습니다. 후속 검색의 변경 접미사가 붙은 문자열은 최초 검색어 비중에 섞지 않았습니다.</p></section>'
    f=d['funnel'];stages=[('결과 없음','0건 결과가 나온 검색',f['zero'],'전체 검색 중',c['searches']),('다시 검색','0건 직후 다음 검색이 있음',f['followup'],'0건 검색 중',f['zero']),('결과 회복','바로 다음 검색에서 결과가 나옴',f['recovered'],'후속 검색 중',f['followup']),('회복 후 클릭','회복한 검색에 호텔 클릭이 있음',f['recovered_click'],'즉시 회복 중',f['recovered'])];steps=[]
    for i,(title,definition,n,base,den) in enumerate(stages):
        ratio=n/den*100;width=n/f['zero']*100
        steps.append(f'<li><div class="funnel-step-name"><span>{i+1:02}</span><div><h3>{title}</h3><p>{definition}</p></div></div><div class="funnel-step-value"><strong>{n:,}<small>건</small></strong><span>0건 검색 대비 {width:.2f}%</span></div><div class="funnel-step-rate"><strong>{ratio:.2f}%</strong><span>{base} {n:,} / {den:,}</span></div><div class="funnel-width" aria-hidden="true"><div style="width:{width}%;background:{colors[i]}"></div></div></li>')
    funnel_svg=[]
    nums=[f['zero'],f['followup'],f['recovered'],f['recovered_click']]
    for i,n in enumerate(nums):
        topw=n/f['zero']*580;botw=(nums[i+1] if i<3 else n)/f['zero']*580;y=20+i*105
        funnel_svg.append(f'<polygon points="{320-topw/2},{y} {320+topw/2},{y} {320+botw/2},{y+80} {320-botw/2},{y+80}" fill="{colors[i]}"><title>{stages[i][0]} {n:,}검색 · 최초 0건 검색 대비 {n/f["zero"]*100:.2f}%</title></polygon><text x="650" y="{y+31}" font-size="18" fill="#20324b">{stages[i][0]} · {n:,}건</text><text x="650" y="{y+59}" font-size="14" fill="#68788a">최초 0건 검색 대비 {n/f["zero"]*100:.2f}%</text>')
    funnel_picture='<div class="analytics-plot"><svg viewBox="0 0 1000 440" role="img" aria-label="결과 없음 이후 전이 퍼널 · 단계 시작 폭은 최초 0건 검색 대비 비율">'+''.join(funnel_svg)+'</svg></div>'
    funnel='<section class="analytics-chart" id="overview-readable-funnel"><div class="analytics-chart-head"><div><span class="analytics-kicker">결과 없음 이후 · 검색 전이 기준</span><h3>다시 검색한 뒤, 어디까지 이어졌나?</h3></div></div><div class="analytics-meta"><span>기간: '+period+'</span><span>대상: 결과 없음 '+format(f['zero'],',')+'검색</span><span>비교: 단계별 진행 건수와 직전 단계 대비 비율</span></div>'+funnel_picture+'<ol class="readable-funnel">'+''.join(steps)+'</ol><p class="meta">막대 길이는 모두 0건 검색 '+format(f['zero'],',')+'건 기준입니다. 오른쪽 비율은 각 단계에 적힌 분모를 사용합니다. 반복 0건 검색도 각각 세므로 사용자 수가 아닙니다. 회복하지 못한 후속 검색과 후속검색이 없는 경우를 실제 서비스 이탈로 단정하지 않습니다.</p></section>'
    # Semantic topic labels are explicit editorial rules over generated first-query terms.
    keyword_map={x['label']:x['n'] for x in d['keywords']}
    groups=[('업무·출장 관련 표현',['business'],(20,20)),('가족 관련 표현',['family'],(520,20)),('주말 관련 표현',['weekend'],(20,350)),('일반 숙소 탐색',['hotel','stay'],(520,350))]
    cloud=[]
    for gi,(name,terms,(x,y)) in enumerate(groups):
        total=sum(keyword_map[t] for t in terms)
        cloud.append(f'<rect x="{x}" y="{y}" width="460" height="300" rx="20" fill="{["#f0f3fc","#edf7f4","#fbf5ea","#f3f0fa"][gi]}"/><text x="{x+25}" y="{y+35}" font-size="19" font-weight="700" fill="#20324b">{name}</text><text x="{x+25}" y="{y+62}" font-size="13" fill="#68788a">{total:,}명 · {total/100:.2f}%</text>')
        for j,term in enumerate(terms):
            n=keyword_map[term];r=88*(n/max(keyword_map.values()))**.5;cx=x+230 if len(terms)==1 else x+125+j*210;cy=y+177
            cloud.append(f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="{colors[gi]}" opacity=".93"><title>{term}: {n:,}명 / 10,000명 · {n/100:.2f}% · 검색어 주제 가분류</title></circle><text x="{cx}" y="{cy-6}" text-anchor="middle" font-size="25" font-weight="700" fill="white">{term}</text><text x="{cx}" y="{cy+23}" text-anchor="middle" font-size="15" fill="white">{n:,}명 · {n/100:.2f}%</text>')
    keywords='<section class="analytics-chart" id="overview-keywords"><span class="analytics-kicker">검색어 버블 · 목적 관련 표현의 가분류</span><h3>어떤 목적의 검색어로 시작했나?</h3><div class="analytics-meta"><span>기간: '+period+'</span><span>분모: 첫 검색 사용자 10,000명</span><span>버블 면적: 검색어별 사용자 수</span></div><div class="word-cloud"><svg viewBox="0 0 1000 675" role="img" aria-label="합성 첫 검색어를 업무·가족·주말·일반 숙소 탐색의 네 주제군으로 가분류한 버블 차트">'+''.join(cloud)+'</svg></div><p class="meta">business→업무·출장, family→가족, weekend→주말, hotel·stay→일반 숙소 탐색으로 묶은 <b>검색어 의미 기반 규칙 분류</b>입니다. 실제 사용자의 여행 목적을 확정하거나 자동 군집화한 결과가 아닙니다.</p><p class="meta">현재 다섯 시작 단어는 합성 생성값입니다. 외부 검색엔진 유입어가 아니며, 예산·옵션 수·위치 유연형 등 기존 <b>6개 조건 변경 의도군</b>과는 다릅니다. 그 6개 의도는 intent_segment와 변경 의향 로그가 없어 배정하지 않았습니다.</p><details><summary>검색어별 원래 건수·비중</summary><ul class="keyword-legend">'+''.join(legend)+'</ul></details></section>'
    cohorts=d['cohort_patterns'];descriptions=['첫 검색 결과가 1개 이상. 이후 실패 경험이 있을 수 있음.','첫 검색 0건 → 다음 검색 존재 → 이후 한 번 이상 결과 있음.','첫 검색 0건 → 다음 검색 존재 → 끝까지 결과 없음.','첫 검색 0건 → 같은 세션의 다음 검색 없음.']
    legend_paths=''.join(f'<span><i style="background:{colors[i]}"></i>{g["label"]} <b>{g["users"]:,}명</b></span>' for i,g in enumerate(cohorts))
    definition_rows=''.join(f'<tr><td>{g["label"]}</td><td>{g["users"]:,}명 · {g["users"]/100:.2f}%</td><td>{descriptions[i]}</td></tr>' for i,g in enumerate(cohorts))
    seq='<section class="analytics-chart" id="overview-depth"><span class="analytics-kicker">세그먼트별 검색 경로 · 10,000명</span><h3>성공과 실패 후 재시도, 검색 경로는 어떻게 달랐나?</h3><div class="analytics-meta"><span>기간: '+period+'</span><span>비교: 첫 검색 결과와 후속 회복 기준 4개 군</span><span>검색 성공: 결과 1개 이상 · 예약 성공 아님</span></div><div class="path-controls" role="group" aria-label="검색 경로 지표"><button data-path-metric="reach" aria-pressed="true">검색 지속</button><button data-path-metric="end" aria-pressed="false">검색 후 종료</button><button data-path-metric="retry" aria-pressed="false">다시 검색</button><button data-path-metric="recovery" aria-pressed="false">0건 후 회복</button></div><p class="path-basis" id="path-basis"></p><div class="path-legend">'+legend_paths+'</div><div id="path-plot" class="analytics-plot"></div><p class="meta">사용자 이탈 기준·관찰창이 명확하지 않아 검색 전이를 분석합니다. 검색 후 종료는 같은 세션의 다음 검색이 없는 경우이며, 상세 탐색·목적 달성·나중 재방문을 구분하지 못하므로 사용자 이탈률로 해석하지 않습니다. 군별 비율로 비교해 표본 수 차이를 보정해 읽습니다. 분모가 없는 순번은 0%로 연결하지 않습니다. 점에 마우스를 올리면 분자·분모를 확인할 수 있습니다.</p><details><summary>세그먼트 판정 기준·표본 수</summary><div class="scroll"><table><thead><tr><th>세그먼트</th><th>표본</th><th>정의</th></tr></thead><tbody>'+definition_rows+'</tbody></table></div><p class="meta">회복 여부는 검색 후 결과를 포함한 사후 분류입니다. 회복군의 곡선을 개입의 인과효과로 해석하지 않습니다. 생성기는 최대 31검색에서 종료되므로 마지막 순번의 종료는 생성 제한의 영향을 받습니다.</p></details><details><summary>현재 선택 지표 · 순번별 분자·분모</summary><div id="path-values"></div></details></section>'
    from visual_analysis import overview_extras
    return head+keywords+overview_extras(root)+trends+composition+experience+funnel+search_experience+seq+foot+'<script id="overview-data" type="application/json">'+json.dumps(d,ensure_ascii=False).replace('</','<\\/')+'</script>'
