// Hotel names and city membership combine the previous tourism-directory catalog
// with named OpenStreetMap accommodation records retrieved on 2026-08-27.
// Rates, ratings, reviews, room features, availability, and inventory are simulations.
export const HOTEL_SUBREGIONS: Record<string, string[]> = {
  Tokyo: ["신주쿠", "시부야", "긴자·도쿄역", "아사쿠사", "우에노", "롯폰기", "오다이바", "시나가와", "이케부쿠로", "니혼바시"],
  Osaka: ["우메다", "난바", "신사이바시", "도톤보리", "혼마치", "텐노지", "오사카성", "신오사카", "베이 에어리어", "교바시"],
  Kyoto: ["교토역", "기온", "가와라마치", "아라시야마", "히가시야마", "니조성", "가라스마", "후시미", "오하라", "교토고쇼"],
  Fukuoka: ["하카타역", "텐진", "나카스", "오호리공원", "모모치", "다자이후", "후쿠오카공항", "야쿠인", "이마이즈미", "우미노나카미치"],
  Sapporo: ["삿포로역", "오도리", "스스키노", "나카지마공원", "마루야마", "모이와산", "신삿포로", "조잔케이", "기타구", "도요히라"],
};
export const REAL_HOTELS: Record<string, string[]> = {
  Tokyo: [
    "Hotel Ueno East",
    "Tokyo Sumidagawa Youth Hostel",
    "Hotel Wing International Premium Tokyo Yotsuya",
    "Shinjuku Washington Hotel",
    "Listel Shinjuku Hotel",
    "Shinjuku Prince Hotel",
    "Sotetsu Fresa Inn Higashi Shinjuku",
    "Hotel Sunroute Plaza Shinjuku",
    "Ryokan Sawanoya",
    "Annex Katsutaro Ryokan",
    "Mandarin Oriental Tokyo",
    "Shibuya Tobu Hotel",
    "The Prince Sakura Tower Tokyo",
    "Hotel Nihonbashi Saibo",
    "Shinagawa Prince Hotel",
    "JR-East Hotel Mets Shibuya",
    "Hyatt Regency Tokyo",
    "InterContinental Tokyo Bay",
    "The Capitol Hotel Tokyu",
    "Hotel Hokke Club Asakusa",
    "Shibuya Tokyu REI Hotel",
    "Hotel Horidome Villa",
    "The Strings by InterContinental Tokyo",
    "Hotel Mystays Hamamatsucho",
    "Hotel JAL City Haneda Tokyo",
    "Richmond Hotel Tokyo Shiba",
    "Dai-ichi Hotel Ryogoku",
    "Mitsui Garden Hotel Ueno",
    "Ochanomizu Inn",
    "Hotel New Otani Tokyo",
    "Palace Hotel Tokyo",
    "The Tokyo Station Hotel",
    "Imperial Hotel Tokyo",
    "Conrad Tokyo",
    "Park Hotel Tokyo",
    "The Okura Tokyo",
    "Andaz Tokyo Toranomon Hills",
    "Grand Hyatt Tokyo",
    "Cerulean Tower Tokyu Hotel",
    "Keio Plaza Hotel Tokyo",
    "Hilton Tokyo",
    "Park Hyatt Tokyo",
    "The Peninsula Tokyo",
    "Four Seasons Hotel Tokyo at Marunouchi",
    "Aman Tokyo",
    "Hoshinoya Tokyo",
    "The Gate Hotel Tokyo by Hulic",
    "Mitsui Garden Hotel Jingugaien Tokyo Premier",
    "sequence Miyashita Park",
    "Tokyo Dome Hotel",
    "＆AND HOSTEL AKIHABARA",
    "&Here",
    "1 Hotel Tokyo",
    "328 Hostel&Lounge",
    "3Q Seasons",
    "3Q Showa",
    "9h nine hours",
    "9h nine hours Hamamatsucho",
    "9h nine hours Otemachi",
    "9h nine hours woman",
    "AC Hotel by Marriott Tokyo Ginza",
    "ACE INN Asakusa",
    "Ace Inn Shinjuku",
    "ACUERUDO",
    "Agora Place Asakusa",
    "Ai Ai House",
    "Ai Hotel Nihonbashi",
    "AIM",
    "aima",
    "air b&b",
    "Air bnb",
    "Airbnb",
    "airbnb Minami Mejiro",
    "Airbnb Oku",
    "Airport Inn",
    "Aizuya-Inn",
    "Akabane Plaza Hotel",
    "Akasaka Tameike Tower",
    "Akasaka Yoko Hotel",
    "Akatsuka International Guiest House",
    "Aki’s Place",
    "Akihabara Washington Hotel",
    "Albida Hotel Aoyama",
    "almeria",
    "Almond Hostel & Cafe",
    "Almont Hotel Nippori",
    "Aloft Tokyo Ginza",
    "AMAND HOTEL",
    "ANA Intercontinental Tokyo",
    "And Hostel Asakusa Kappabashi",
    "And Hostel Kuramae West",
    "ANdAZ",
    "Andon Ryokan",
    "Anne Hostel Asakusabashi",
    "Anne Hostel Yokozuna",
    "Anshin Oyado",
    "Anshin Oyado Shimbash",
    "AOBADAI FORUM",
    "Aoki House",
    "APA Hotel",
    "APA hotel (Shinjuku Kabukicho Chuo)",
    "APA Hotel & Resort (Tokyo Bay Makuhari)",
    "APA Hotel ＆ Resort Yokohama Bay Tower",
    "APA Hotel Asakusa Kuramae",
    "APA Hotel Asakusa Shin-Okachimachi Ekimae",
    "APA Hotel Ginza Shintomicho Ekimae",
    "APA Hotel Ginza Shintomicho Ekimae Kita",
    "APA Hotel Ginza-Kyobashi",
    "Apa Hotel Ginza-Takaracho",
    "APA Hotel Haneda Anamori Inari Ekimae",
    "APA Hotel Hatchobori Eki Minami",
    "APA Hotel Jimbocho",
    "APA Hotel Kanda-Ekimae",
    "APA Hotel Machida-ekihigashi",
    "APA Hotel Nihonbashi Bakurocho-eki Kita",
    "Apa Hotel Ningyocho Ekihigashi",
    "APA Hotel Pride Kokkaigijidomae No.293",
    "APA Hotel Shibuya Dogenzakaue",
    "APA Hotel Shimbashi Onarimon",
    "APA Hotel Shinagawa Sengakuji-Ekimae",
    "APA Hotel Tokyo Kiba",
    "APA Hotel Tokyo-Shiomi-Ekimae",
    "APA Hotel Tsukiji-Eki Minami",
    "APA Hotel Ueno Ekikita",
    "APA Hotel 茅場町八丁堀駅前",
    "APA VILLA HOTEL",
    "Appt Ikebukuro",
    "Aqua Suites",
    "Arcadia Ichigaya (Shigaku Kaikan)",
    "Arche de Reve Hotel",
    "ARK TOWER",
    "Asaka Daily Hotel",
    "Asakusa Hotel Fukudaya",
    "Asakusa Hotel Hatago",
    "ASAKUSA KAEDE 浅草楓",
    "Asakusa Smile",
    "Asakusa View Hotel",
    "Asakusabashi Business Hotel",
    "Asausa Edo no Mai",
    "Asia Center of Japan",
    "Avanshell Akasaka",
    "Azur Takeshiba",
    "Badmaa bair",
    "Ban Hotel Tsukiji Ginza",
    "Beagie Tokyo Hostel & Apartment",
    "Beginning Guest House",
    "Belken Hotel Kanda",
    "BELLUSTAR TOKYO, A Pan Pacific Hotel",
    "Best Western Hotel Fino Tokyo Akihabara",
    "Best Western Tokyo Akasaka",
    "Best Western Tokyo Nishikasai Grande",
    "Bettei.Zen墨田",
    "Big Hills 21",
    "Block Room",
    "Blossom Shinjuku",
    "BLUMEN HEIM",
    "bmj Hyakunincho",
    "BnA_WALL - The BnA ART HOTEL",
    "Book and Bed Shinjuku",
    "Borderless House Honkomagome1",
    "Borderless House Shinjuku-Honancho1",
    "buc",
    "Bulgari Hotel Tokyo",
    "BUNKA HOSTEL TOKYO",
    "Bureau Kioicho",
    "Business Hotel Inamoto",
    "Business Hotel Legato",
    "Business Hotel Sunlight",
    "BUSINESS HOTEL サンライト 別館",
    "Business Inn Ryogetsu",
    "BusinessHotel Fukudaya",
    "C’est la vie Room 101",
    "C201",
    "Canal",
    "Candeo Hotel",
    "Candeo Hotels",
    "Candeo Hotels Tokyo Shimbashi",
    "Capsule Hotel & Sauna: Cosmo Plaza Akabane",
    "Capsule Hotel Anshin Oyado",
    "capsule hotel et sauna",
    "Capsule hotel FK",
    "CaPsuLe Inn Akasaka",
    "Capsule Inn Hamamatsucho",
    "Capsule Inn Tamachi",
    "Capsule Land Yushima",
    "capsule net OMOTENASHI no OYADO",
    "Capsule Value Kanda",
    "Casa de Eigo - depto 606",
    "Celestine Hotel",
    "Centurion Hotel",
    "Centurion Hotel Grand",
    "Centurion Hotel Tower",
    "Centurion Hotel Ueno",
    "Centurion Hotel Vintage",
    "CENTURION LADIES HOSTEL",
    "Century Southern Tower Hotel",
    "Cerulean Tower Tokyo Hotel",
    "Charire",
    "Chinsan-zo",
    "Chisun Hotel",
  ],
  Osaka: [
    "Hotel Granvia Osaka",
    "InterContinental Osaka",
    "Conrad Osaka",
    "Osaka Marriott Miyako Hotel",
    "The Ritz-Carlton Osaka",
    "Imperial Hotel Osaka",
    "RIHGA Royal Hotel Osaka",
    "Hilton Osaka",
    "Swissotel Nankai Osaka",
    "Hotel New Otani Osaka",
    "Cross Hotel Osaka",
    "Hotel Nikko Osaka",
    "Centara Grand Hotel Osaka",
    "W Osaka",
    "Zentis Osaka",
    "The Royal Park Hotel Iconic Osaka Midosuji",
    "Mitsui Garden Hotel Osaka Premier",
    "Hotel Monterey Grasmere Osaka",
    "Hotel Monterey Le Frere Osaka",
    "Hotel Hankyu Respire Osaka",
    "Hotel Intergate Osaka Umeda",
    "Hotel Vischio Osaka",
    "Hearton Hotel Nishi Umeda",
    "Daiwa Roynet Hotel Osaka Kitahama",
    "Hotel Sun White",
    "Hotel Hillarys",
    "Travelodge Honmachi Osaka",
    "Hotel Trusty Osaka Abeno",
    "Dormy Inn Premium Osaka Kitahama",
    "Rihga Place Higobashi",
    "Osaka Excel Hotel Tokyu",
    "Courtyard by Marriott Shin-Osaka Station",
    "karaksa hotel grande Shin-Osaka Tower",
    "Holiday Inn Express Osaka City Centre Midosuji",
    "Citadines Namba Osaka",
    "Fraser Residence Nankai Osaka",
    "Hotel Keihan Namba Grande",
    "Candeo Hotels Osaka Namba",
    "Agora Place Osaka Namba",
    "Sotetsu Grand Fresa Osaka Namba",
    "Mercure Tokyu Stay Osaka Namba",
    "The Lively Osaka Honmachi",
    "Moxy Osaka Honmachi",
    "Moxy Osaka Shin Umeda",
    "Aloft Osaka Dojima",
    "Hotel Universal Port",
    "The Park Front Hotel at Universal Studios Japan",
    "Liber Hotel Osaka",
    "Quintessa Hotel Osaka Bay",
    "Art Hotel Osaka Bay Tower",
    "-桜時雨- 新大阪",
    "&Here OSAKA NAMBA",
    "1 Chome-7-5 Ōmiya, Asahi-ku, Ōsaka-shi, Ōsaka-fu",
    "373グループハウス",
    "AB HOTEL",
    "ACRO Capsule Hotel",
    "Air Osaka Hostel",
    "Airbnb",
    "AManTo guest house",
    "Amemura",
    "AMZA",
    "APA Hotel",
    "APA Hotel & Resort Osaka Namba Ekimae Tower",
    "APA Hotel & Resort Osaka Umeda Eki Tower",
    "APA hotel <Osaka Higobashi Ekimae>",
    "APA Hotel Namba Shinsaibashi",
    "APA Hotel Namba-Ekihigashi",
    "APA Hotel Namba-Shinsaibashi-Nishi",
    "APA Hotel Tennoji Ekimae",
    "APA Hotel Yodoyabashi Ekimae",
    "Apa Vila hotel",
    "Apartment Hotel 11 Namba Minami 5",
    "Apartment Hotel 11 Namba Minami Shin-Imamiya",
    "Arashi",
    "Ashiya Baycourt Club Hotel & Spa Resort",
    "ASTIL HOTEL",
    "Backstage Osaka Hostel & Bar",
    "BAL",
    "Bali An RESORT",
    "Bali Tower",
    "BANDE HOTEL OSAKA",
    "BANDE HOTEL TENPOZAN",
    "Blue Bee Sakuragawaekimae",
    "Brackets Hotel",
    "Business hotel Lucky",
    "Business Hotel New Ohama",
    "Business Hotel Taiyo",
    "Business Hotel Takasagoya",
    "Business Hotel Urbanty Nishi-Kujo",
    "Business Inn Sennichimae Hoteleed",
    "CANDEO HOTELS",
    "Candeo Hotels Osaka The Tower",
    "Canopy by Hilton Osaka Umeda",
    "Capsule Hotel Asahi Plaza",
    "Centara Grand Hotel",
    "Cityplaza Osaka",
    "Cityroute Hotel",
    "COCOROOM",
    "Comfort Hotel Osaka Sinsaibashi",
    "Confort Hotel Shin-Osaka",
    "Consort",
    "Cordia",
    "Daihatsu Kouda Ryo Dormitory",
    "Daiwa Roynet Hotel",
    "Daiwa Roynet Hotel Osaka-Kitahama",
    "DEL style大阪新梅田",
    "DEL style大阪新梅田ANNEX",
    "Dojima Hotel",
    "dormy inn hotel",
    "Dormy Inn Osaka Tanimachi",
    "Dormy Inn Premium Nanba",
    "Dormy Inn Shinsaibashi",
    "Dormy Inn Umeda Higashi",
    "Dotombori Shinsaibashi Hotel",
    "DOTONBORI HOTEL",
    "DoubleTree by Hilton Osaka Castle",
    "Dream Stays TSUKI",
    "Dynasty Hotel",
    "EARTHMANS AMEMURA",
    "EI Building",
    "ELEGANCE",
    "esports hotel e-ZONe ～電脳空間～",
    "EXCEL HOTELTOKYU",
    "EXE東心斋橋",
    "Fairfield by Marriott Osaka Namba",
    "FDS AIM (FDS エイム)",
    "fine garden",
    "FL Hotel Dotonbori",
    "FLORAL HOTEL SAKAISUJI-HONMACHI",
    "FOR  LEAVES INN",
    "FOUR POINTS FLEX BY SHERATON",
    "Four Seasons Hotel Osaka",
    "FP Hotels",
    "Fraser Residence Nankai",
    "Fuku Hostel",
    "Fukunoya Ryokan",
    "Galliano",
    "Gemini",
    "GOEMON",
    "Grand Hotel Osaka",
    "Grand Prince Hotel Osaka Bay",
    "Green Rich Hotel",
    "Green Village Katano",
    "Guest House ANCHOR",
    "Guest House Bed&Bicycle",
    "Guest House Kishinosato",
    "Guest House Mii",
    "Guest House Mutsu",
    "GUEST HOUSE Rice",
    "Guest House Siam",
    "Guest House Tennoji 168",
    "Guesthouse En Sagisu",
    "H2H Osaka Castle",
    "Hana Hostel Osaka",
    "Hanna Country Club",
    "Hawk on pine tree",
    "Hearton Hotel",
    "Hearton Hotel Nishiumeda",
    "Hearton Hotel Shinsaibashi",
    "Hearton Hotel Shinsaibashi Annex",
    "Henn na Hotel",
    "Hikari House Shin-Osaka",
    "Hirakata Sun Plaza Hotel",
    "Hitsujiya Ryokan",
    "Hiyori Hotel",
    "Hokousou",
    "Holiday Inn Osaka Namba",
    "Holiday Pearl Hotel",
    "Home",
    "HOME HOSTEL OSAKA",
    "Hostel Bushi",
    "Hostel Furoya",
    "HOSTEL JIN",
    "Hostel Kai Osaka",
    "Hostel MOKUMOKU",
    "Hostel OGK",
    "Hostel OSAKA",
    "Hostel Osaka 64",
    "Hostel Takeyado",
    "HostelQ",
    "Hotel 3 O'Clock",
    "Hotel 88 Shinsaibashi",
    "Hotel A.P",
    "Hotel AGORA",
    "Hotel Alexander Namba",
    "Hotel Alps",
    "Hotel Alten",
    "Hotel Amaterrace 縁",
    "hotel androoms",
    "Hotel atarayo Osaka",
    "HOTEL ATLANTIS",
    "HOTEL AVANCER 天満",
    "HOTEL B Suites",
    "Hotel Balian Resort Namba Shinsaibashi",
    "HOTEL BINARIO UMEDA",
    "Hotel Brighton City Osaka Kitahama",
    "Hotel C-Gran 藤井寺",
    "HOTEL CEEDS",
    "Hotel Chuo Selene",
    "HOTEL CORDIA OSAKA",
  ],
  Kyoto: [
    "Hotel Granvia Kyoto",
    "RIHGA Royal Hotel Kyoto",
    "Hyatt Regency Kyoto",
    "Hotel Hokke Club Kyoto",
    "The Thousand Kyoto",
    "Kyoto Century Hotel",
    "Hotel Keihan Kyoto Grande",
    "Sakura Terrace",
    "Kyoto Tokyu Hotel",
    "Kyoto Plaza Hotel",
    "Dormy Inn Premium Kyoto Ekimae",
    "Almont Hotel Kyoto",
    "Hotel Gracery Kyoto Sanjo",
    "The Prince Kyoto Takaragaike",
    "Miyako City Kintetsu Kyoto Station",
    "Ibis Styles Kyoto Station",
    "Mitsui Garden Hotel Kyoto Shijo",
    "Mitsui Garden Hotel Kyoto Kawaramachi Jokyoji",
    "The Westin Miyako Kyoto",
    "The Ritz-Carlton Kyoto",
    "ROKU Kyoto LXR Hotels & Resorts",
    "Dusit Thani Kyoto",
    "Park Hyatt Kyoto",
    "Four Seasons Hotel Kyoto",
    "Aman Kyoto",
    "Ace Hotel Kyoto",
    "Hotel Okura Kyoto",
    "ANA Crowne Plaza Hotel Kyoto",
    "Kyoto Brighton Hotel",
    "Hotel Nikko Princess Kyoto",
    "Solaria Nishitetsu Hotel Kyoto Premier",
    "Kyoto Granbell Hotel",
    "Kyoto Tower Hotel",
    "Kyoto Tower Hotel Annex",
    "The Royal Park Hotel Kyoto Umekoji",
    "The Royal Park Canvas Kyoto Nijo",
    "Oakwood Hotel Oike Kyoto",
    "Fauchon Hotel Kyoto",
    "Suiran a Luxury Collection Hotel Kyoto",
    "Dhawa Yura Kyoto",
    "Hotel Tavinos Kyoto",
    "Hotel The M's Kyoto",
    "Hotel M's Plus Shijo Omiya",
    "Sequence Kyoto Gojo",
    "Oriental Hotel Kyoto Rokujo",
    "Karaksa Hotel Kyoto I",
    "Urban Hotel Kyoto Shijo Premium",
    "Kyoto Hot Spring Hatoya Zuihokaku Hotel",
    "Mimaru Kyoto Station",
    "Mimaru Suites Kyoto Central",
    "&haku",
    "519 Kitakinomotochō",
    "828 Kyoto",
    "9hours Kyoto",
    "ABホテル 京都四条堀川",
    "add.hostel",
    "AKARI二条城",
    "Amber House Gion",
    "ANA Crowne Plaza Kyoto",
    "ANGO",
    "Aoi Hotel Kyoto",
    "APA GARDEN COURT 烏丸錦",
    "APA Hotel",
    "APA Hotel Gion",
    "APA Hotel Horikawadori",
    "APA Hotel Kyoto Gojo Omiya",
    "Apartment",
    "APAホテル京都駅前中央口",
    "Arashiyama Benkei hotel",
    "Arc Hotel",
    "ASAI Kyoto Shijo",
    "Atagoya guest house",
    "Ayaha Lake Side Hotel",
    "Ayome 文月",
    "Azure Nijo Kyoto House",
    "Banyan Tree Higashiyama Kyoto",
    "Biwako Hotel",
    "Biwako Raken Hotel Izutsu",
    "BJ Family House",
    "Bochi bochi karasuma",
    "Brighton Hotel Kyoto",
    "Briller Kyoto Tambaguchi",
    "Buddha House",
    "Budget Inn Kyoto",
    "Caesar Gion Kyoto",
    "CANDEO Hotels",
    "Capsule Ryokan Kyoto",
    "Chion-In Wajun-Kaikan",
    "Chisun Premium Kyoto Kujo",
    "Chloris",
    "CHO-AN",
    "CMM Monthly Mansions Horikawa Sanjou 堀川三条",
    "cocoon Kyoto 東山七条",
    "Comfort Hotel ERA Kyoto Toji",
    "Comfort Hotel Kyoto Horigawagojo",
    "Comfort INN",
    "Comicap Kyoto",
    "Connect inn 京都東山",
    "CROSS HOTEL KYOTO",
    "Daiwa Roynet Hotel",
    "Daiwa Roynet Hotel Kyoto Shijo Karasuma",
    "Daiya ryokan",
    "Discover Nagaokakyo",
    "Dorm Kamogawa",
    "DoubleTree by Hilton Kyoto Higashiyama",
    "DoubleTree by Hilton Kyoto Station",
    "Ebisu Ryokan",
    "Econo inn",
    "EHON HOUSE",
    "Elite Inn Kyoto Station",
    "Enryakuji Kaikan",
    "Enso Machiya",
    "Epoch Inn Fushimi Inari",
    "Fauchon L’Hôtel Kyoto",
    "First cabin",
    "First Cabin Kyoto Kawaramachi Sanyo",
    "First Cabin Kyoto-Karasuma",
    "Four Seasons Hotel",
    "FRESA INN",
    "FUFU Kyoto",
    "Fujitaya BnB",
    "Fujiya ryokan",
    "Garden Ryokan Yachiyo",
    "Garner Hotel Kyoto Shijo Karasuma by IHG",
    "Gate 80",
    "Genji Kyoto",
    "Gino",
    "Gion Misen",
    "Gion united hotel",
    "GLANZKEI Kyoto Station",
    "GO",
    "Gojo guest house annex",
    "Gojo-Muromachi Japan Hotel",
    "Good day kyoto",
    "GOOD NATURE STATION",
    "Gozan hotel",
    "Green Rich Hotel",
    "GRIDS Kawaramachi",
    "Guest House Bokuyado",
    "Guest house Jiyu-jin",
    "Guest House Kioto",
    "GUEST HOUSE KYO-KOI NISHIKI",
    "Guest House Kyoto",
    "GUEST HOUSE KYOTO UJIGAWA",
    "GUEST HOUSE YAMATO",
    "Guest-inn ちた (Guest Inn Chita)",
    "Guesthouse Gekkousou",
    "Guesthouse Hyakumanben Cross",
    "Guesthouse Itoya",
    "Guesthouse Kingyo-ya",
    "Guesthouse Kyoto Ekimae",
    "Guesthouse Mew",
    "Guesthouse Mundo",
    "Guesthouse OKI's Inn",
    "Guesthouse Origami",
    "Guesthouse Oumi",
    "Guesthouse Rakutendo",
    "Guesthouse Venten",
    "GUESTHOUSE地球号",
    "HANA HOTEL",
    "Hanayashiki Ukifune-En",
    "Hanazono Kaikan",
    "Hat'n Hat Hostel",
    "HATSUNE GUESTHOUSE",
    "Hearton Hotel Kyoto",
    "Henn na Hotel Premier Kyoto Gojo Karasuma",
    "Hiei Mountain House",
    "Hifumi ryokan",
    "HIGASHIYAMA 恵庵",
    "Hilton Garden Inn Kyoto Shijo Karasuma",
    "Hilton Kyoto",
    "Hiroya",
    "HIYORI STAY KYOTO KAMOGAWA",
    "HIZ",
    "Holiday Inn Kyoto Gojo by IHG",
    "HOMANN CONCEPT KYOTO",
    "Homm Stay Nagi Arashiyama Kyoto",
    "Homm Stay Nagi Sanjo Kyoto",
    "Homm Stay Nagi Shijo Kyoto",
    "Hop Inn Kyoto Shijo Omiya",
    "HOPE TREE 京都",
    "HOSHINO OMO5 Kyoto sanjo",
    "HOSHINOYA Kyoto",
    "HOSHINOYA Kyoto Boat Landing",
    "Hostel Ginkakujiホステル銀閣寺",
    "Hostel HARUYA Aqua",
    "Hostel HARUYA KYOTO",
    "Hostel Kyotokko",
    "Hostel Otro Mundo",
    "Hostel Sui Kyoto",
    "Hotel ABEST Grande Kyoto Kiyomizu",
    "HOTEL ALFA LUXURY SWEET",
    "Hotel Androoms",
    "Hotel Anteroom Kyoto",
    "HOTEL ARU KYOTO 三条木屋町通り",
    "hotel Bell・Kyoto（ホテルベル京都）",
    "Hotel Binario Saga Arashiyama",
    "Hotel Blue Lake Otsu",
    "Hotel Brighton City",
    "Hotel Canata Kyoto",
  ],
  Fukuoka: [
    "Oriental Hotel Fukuoka Hakata Station",
    "Hakata Green Hotel No.1",
    "Miyako Hotel Hakata",
    "Hotel Clio Court Hakata",
    "Richmond Hotel Hakata Ekimae",
    "Comfort Hotel Hakata",
    "Hakata Green Hotel Annex",
    "Yaoji Hakata Hotel",
    "Solaria Nishitetsu Hotel Fukuoka",
    "JR Kyushu Hotel Blossom Fukuoka",
    "Hotel Resol Trinity Hakata",
    "Dukes Hotel Hakata",
    "S-Peria Hotel Hakata",
    "Hotel Nikko Fukuoka",
    "The Luigans Spa & Resort",
    "The Breakfast Hotel Fukuoka Nakasu",
    "Hotel Il Palazzo",
    "Grand Hyatt Fukuoka",
    "Hilton Fukuoka Sea Hawk",
    "The Ritz-Carlton Fukuoka",
    "Mitsui Garden Hotel Fukuoka Gion",
    "Mitsui Garden Hotel Fukuoka Nakasu",
    "Nishitetsu Hotel Croom Hakata",
    "Nishitetsu Grand Hotel",
    "Hotel Okura Fukuoka",
    "The Royal Park Hotel Fukuoka",
    "Hotel Forza Hakataeki Chikushi-Guchi I",
    "Hotel Forza Hakataeki Hakataguchi",
    "Dormy Inn Premium Hakata Canal City Mae",
    "Dormy Inn Hakata Gion",
    "Tokyu Stay Hakata",
    "ANA Crowne Plaza Fukuoka",
    "Crowne Plaza ANA Fukuoka",
    "The Basics Fukuoka",
    "With The Style Fukuoka",
    "Hotel Wing International Select Hakata Ekimae",
    "Hotel Monte Hermana Fukuoka",
    "Hotel Monterey La Soeur Fukuoka",
    "Quintessa Hotel Fukuoka Tenjin",
    "Candeo Hotels Fukuoka Tenjin",
    "lyf Tenjin Fukuoka",
    "Lamp Light Books Hotel Fukuoka",
    "Cross Life Hakata Tenjin",
    "Cross Life Hakata Yanagibashi",
    "Prince Smart Inn Hakata",
    "Via Inn Hakataguchi Ekimae",
    "JR Kyushu Hotel Blossom Hakata Central",
    "Hakata Tokyu REI Hotel",
    "Hotel WBF Grande Hakata",
    "Agora Fukuoka Hilltop Hotel & Spa",
    "9h nine hours Hakata Station",
    "Accord Hotel",
    "ANA Crowne Plaza Hotel Fukuoka",
    "APA Hotel",
    "APA Hotel Hakataeki Chikushiguchi",
    "Best Western Plus Fukuoka Tenjin",
    "Business One Tenjin",
    "Candeo Hotels",
    "Cloud Sharing Hotel",
    "Comfort INN",
    "common de",
    "CON PATIO",
    "Court Hotel Fukuoka Tenjin",
    "Cross Life",
    "CRYSTAL&RESORT FUKUOKA",
    "Daiwa Roynet Hotel Hakata-Gion",
    "Dormy Inn Premium Hakata Canal City-mae",
    "Dottor Hotel Hakata",
    "Dukes Hotel",
    "FOUR POINTS FLEX",
    "Fukuoka Guesthouse CAMP",
    "Fukuoka Guesthouse SHIP",
    "Fukuoka Prince Hotel Momochihama",
    "Fukuoka Sun Palace Hotel & Hall",
    "goomマンスリー福岡天神NS",
    "Grand Base 博多シティ",
    "Guest House Kaine",
    "Guest House Nakaima",
    "Guesthouse Hokorobi",
    "Hakata Business Hotel",
    "Hakata Green Hotel Ichigokan",
    "Hakata Terminal Hotel",
    "HAKOZAKI GARDEN",
    "Hana Hostel",
    "Hataka Wings",
    "HEARTSカプセルホテル&スパ博多",
    "Henn na Hotel",
    "Hilltop resort Fukuoka",
    "HOTEL ACTIVE!",
    "Hotel AZ",
    "HOTEL AZ 福岡金の隈店",
    "Hotel Cabinas Fukuoka",
    "Hotel Century Art",
    "HOTEL CULTIA DAZAIFU",
    "HOTEL CULTIA DAZAIFU　KOUKOTEI棟 & BAIKA棟",
    "Hotel Dormy Inn",
    "Hotel Etwas Tenjin",
    "Hotel Forza Hakata-Guchi",
    "Hotel Grandolce Hakata",
    "Hotel Hakata Place",
    "HOTEL HALROTTO",
    "HOTEL ICHIRAKU",
    "HOTEL JAL CITY",
    "HOTEL KAI",
    "Hotel Leopalace Hakata",
    "HOTEL Love Joy",
    "Hotel Port Hills",
    "Hotel Resol Hakata",
    "Hotel Shingu",
    "HOTEL STAR RISE",
    "Hotel Sunroute Hakata",
    "Hotel Sweety",
    "Hotel Torifito Hakata Gion",
    "Hotel Unizo",
    "Hulaton",
    "JR Kyusyu Hotels Blossom Hakata Chuo",
    "JUSTINFUKUOKA",
    "Kashima Honkan",
    "Khaosan Fukuoka",
    "KKR Hotel Hakata",
    "KOKO Hotel 博多駅",
    "Legatio Hakata",
    "LILY HOUSE",
    "Millenials Hakata",
    "Mistui Garden hotel",
    "Naraya",
    "Nose Phoenix",
    "Oriental Hotel",
    "Park Side Tenjin",
    "Plaza Hotel Tenjin",
    "R&B",
    "Residence Hotel",
    "Riverfront Hakata",
    "RiviL HAKATA",
    "Route Inn Hotel",
    "Royal Park Hotel",
    "Ryokan Masuya",
    "SANCEUR油山",
    "Sanshainsusaki",
    "SBホテル",
    "Seaside Hotel Cion",
    "Sharely Style Hakata",
    "Shizutetsu Hotel Prezio Hakataekimae",
    "Smile Hotel Hakata Ekimae",
    "Solaria Nishitetsu",
    "Stay Inn",
    "Sun Life Hotel 2,3",
    "Tabicolle Backpackers",
    "The B Fukuoka Tenjin",
    "The B Hakata",
    "The Blossom Hakata Premier",
    "The Grand Residence Hakata",
    "THE HOTELS HAKATA Kasane Bayside",
    "The Lively",
    "the pisces inn",
    "The358",
    "Toho hotel Nakasu",
    "Tokyo Stay Hakata",
    "TOKYU STAY",
    "Toyo Hotel",
    "Toyoko Inn",
    "Toyoko Inn Fukuoka Tenjin",
    "Toyoko Inn Hakata-eki Bus-Terminal Mae",
    "Twins Momochi",
    "UNPLAN",
    "URUFU AKASAKA",
    "VESSEL INN FUKUYAMA-EKIKITAGUCHI",
    "Washington Hotel",
    "Washington R&B Hotel Hakataekimae Daiichi",
    "Weekly Inn南福岡",
    "Wellcabin Tenjin",
    "Yamamoto Ryokan",
    "ZONK hotel Hakata",
    "위클리멘션",
    "アークホテルロイヤル福岡天神",
    "ウイークリーイン・二日市",
    "エルカーサ南福岡",
    "エルスタンザ天神東",
    "クインテッサホテル",
    "クインテッサホテル福岡天神",
    "グランドエンパイアホテル",
    "グランビュー福岡空港",
    "ゲストハウス",
    "こみね",
    "サットンホテル",
    "サンコーポフジ",
    "サンビジネスホテル",
    "サンライズマンション東油山",
    "スカイシャトレ柚須",
    "スタシオン名島フォレストヒルズ",
    "ソロン名島",
    "なお AirBnB",
    "ニューガイア",
    "ポートハウス天神",
    "ホテル ニューガイア",
    "ホテル フロント・イン福岡空港",
    "ホテル モンテ エルマーナ福岡",
    "ホテルAZ 福岡和白店",
    "ホテルコピア",
    "ホテルサンライン福岡",
  ],
  Sapporo: [
    "JR Tower Hotel Nikko Sapporo",
    "Sapporo Grand Hotel",
    "Sapporo Prince Hotel",
    "Keio Plaza Hotel Sapporo",
    "ANA Crowne Plaza Sapporo",
    "Mercure Sapporo",
    "Cross Hotel Sapporo",
    "Hotel Monterey Edelhof Sapporo",
    "Century Royal Hotel Sapporo",
    "Solaria Nishitetsu Hotel Sapporo",
    "JR Inn Sapporo",
    "JR Inn Sapporo South",
    "Mitsui Garden Hotel Sapporo",
    "Mitsui Garden Hotel Sapporo West",
    "Hotel Gracery Sapporo",
    "Tokyu Stay Sapporo",
    "Tokyu Stay Sapporo Odori",
    "Sapporo Tokyu REI Hotel",
    "The Royal Park Canvas Sapporo Odori Park",
    "Karaksa Hotel Sapporo",
    "La'gent Stay Sapporo Odori Hokkaido",
    "Dormy Inn Premium Sapporo",
    "Dormy Inn Sapporo Annex",
    "Vessel Inn Sapporo Nakajima Park",
    "Vessel Hotel Campana Susukino",
    "Premier Hotel Nakajima Park Sapporo",
    "Premier Hotel Tsubaki Sapporo",
    "Ibis Styles Sapporo",
    "Quintessa Hotel Sapporo",
    "Quintessa Hotel Sapporo Susukino",
    "Randor Residential Hotel Sapporo Suites",
    "Hotel Mystays Sapporo Aspen",
    "Hotel Mystays Premier Sapporo Park",
    "Hotel Mystays Sapporo Station",
    "Hotel Emisia Sapporo",
    "Sapporo View Hotel Odori Park",
    "Royton Sapporo",
    "Sapporo Park Hotel",
    "Hotel Resol Trinity Sapporo",
    "Hotel Resol Sapporo Nakajima Park",
    "Tenza Hotel & Skyspa at Sapporo Central",
    "OMO3 Sapporo Susukino by Hoshino Resorts",
    "Sapporo Excel Hotel Tokyu",
    "Fairfield by Marriott Sapporo",
    "Courtyard by Marriott Sapporo",
    "The Knot Sapporo",
    "Stream Hotel Sapporo",
    "Hotel Wing International Sapporo Susukino",
    "Comfort Hotel Sapporo Susukino",
    "Richmond Hotel Sapporo Odori",
    "41 PIECES",
    "Affetto",
    "Affetto annexe",
    "ALPHABED INN 札幌大通公園",
    "ANA Holiday Inn Sapporo Susukino",
    "APA HOTEL Sapporo Odori ekimae minami",
    "APA Hotel Sapporo Odori ekimae nishi",
    "APA HOTEL SAPPORO-SUSUKINO-EKIMAE",
    "APA HOTEL SAPPORO-SUSUKINO-EKINISHI",
    "APA HOTEL〈TKP SAPPOROEKI-KITAGUCHI〉EXCELLENT",
    "APA HOTEL<TKP SAPPORO-EKIMAE>",
    "Arura Sapporo",
    "Asano Hotel",
    "Backpackers Hostel INO'S PLACE",
    "bespoke hotel sapporo",
    "Comfort Hotel ERA Sapporo North",
    "Daiwa Roynet Hotel Sapporo Nakajima Koen",
    "Daiwa Roynet Hotel SAPPORO-SUSUKINO",
    "Dansetsu Sapporo",
    "Dreamhouse R&D Gakuenmae",
    "Ezo Run",
    "FRAME HOTEL SAPPORO",
    "GRANBELL HOTEL TANUKI, SAPPORO",
    "Grand Mercure Sapporo Odori Park",
    "GRIDS Sapporo",
    "Guest House On My Way",
    "Guest House Sapporo yuyu",
    "HELIO HOSTEL SAPPORO",
    "Hokkaido Christian Center",
    "Hokkaido Sun Guest House",
    "Holiday Inn & Suites Sapporo Odori Park",
    "Hotel Abest Sapporo",
    "hotel androoms Sapporo Susukino",
    "Hotel Bougainvillea Sapporo",
    "Hotel Classe Stay Sapporo",
    "Hotel Emion Sapporo",
    "HOTEL FORZA SAPPORO-EKIMAE",
    "HOTEL HAMILTON SAPPORO",
    "Hotel Hashimoto",
    "Hotel Hokke Club Sapporo",
    "Hotel JAL City Sapporo Nakajima Park",
    "HOTEL KEIHAN SAPPORO",
    "Hotel Kotoni Sapporo",
    "Hotel la mer",
    "Hotel Lifort Sapporo",
    "HOTEL LiVEMAX",
    "HOTEL LiVEMAX PREMIUM Sapporo Odori koen",
    "HOTEL LiVEMAX SAPPORO NAKAJIMA KOEN GRANDE",
    "Hotel LiVEMAX Sapporo-Ekimae",
    "Hotel Mystays Sapporo eki Kitaguchi",
    "HOTEL MYSTAYS Sapporo Nakajima Park",
    "HOTEL MYSTAYS Sapporo Nakajima Park Annex",
    "Hotel Mystays Sapporo Susukino",
    "Hotel Nets Sapporo",
    "Hotel Nolte",
    "Hotel North City",
    "Hotel ONE'S RESIDENCE",
    "Hotel Pearl City Sapporo",
    "Hotel Polestar Sapporo",
    "Hotel Relief SAPPORO SUSUKINO",
    "HOTEL RESOL SAPPORO NAKAJIMAKOUEN",
    "Hotel rio",
    "Hotel Ronshan Sapporo",
    "HOTEL ROUTE-INN",
    "Hotel Route-Inn Sapporo Ekimae",
    "HOTEL ROYAL STAY SAPPORO",
    "Hotel Sapporo Garden Palace",
    "Hotel Sapporo Met's",
    "Hotel show sapporo",
    "HOTEL Sosei Sapporo M Gallery",
    "Hotel Tetora Split Sapporo",
    "Hotel Tokeidai",
    "Hotel Vista Sapporo",
    "Hotel Vista Sapporo Odori",
    "Hotel Water Gate Timeless Resort",
    "Hotel WBF Sapporo Chuo",
    "Hotel Yukita",
    "ＨＯＴＥＬＷｅｇｏヒラギシ",
    "ＨＯＴＥＬＷＯＯＰａｒｔ－１",
    "ＨＯＴＥＬＷＯＯＰａｒｔ－2",
    "Hoteru WBF Sapporo Susukino",
    "ibis Styles Sapporo hotel",
    "IGLOO",
    "InterContinental Sapporo",
    "Itsukiya",
    "Jasmac Plaza Hotel",
    "JR East Hotel Mets Premier Sapporo",
    "JR INN Sapporo N2",
    "Karakusa Hotel Sapporo",
    "Keikyu EX Hotel Sapporo",
    "Keio Prelia Hotel Sapporo",
    "KOKO HOTEL Sapporo ekimae",
    "KOKO HOTEL Sapporo Odori",
    "La'gent Stay SAPPORO-ODORI",
    "LAMP LIGHT BOOKS HOTEL sapporo",
    "LEAF",
    "Mezamashi Sandwich",
    "Mon lapin",
    "Nakamuraya Ryokan",
    "Nest Hotel Sapporo Odori",
    "New Budget Sapporo",
    "New Otani Inn Sapporo",
    "Nikoh Refre",
    "Odysis Sapporo Odori Park Hotel",
    "OMO3札幌すすきの",
    "Onsen Ryokan Yuen Sapporo",
    "plat hostel keikyu sapporo ichiba",
    "Premier Hotel CABIN Sapporo",
    "Quintessa Hotel Sapporo Susukino 63 Relax＆Spa",
    "QUINTESSA SAPPORO",
    "R&B HOTEL SAPPORO KITA 3 NISHI 2",
    "Richimond Hotel Sapporo Odori",
    "RichmondHotel Sapporo Ekimae",
    "Riverside Hotel Sapporo",
    "Ryokan Fuyoukan",
    "San Gran Hotel Sapporo Odori Koen",
    "Santa island",
    "SappoLodge",
    "Sapporo Clark Hotel",
    "Sapporo Fun Gate Hotel",
    "Sapporo Hotel by Granbell",
    "Sapporo Hotel Yamachi",
    "Sapporo House Seminar Center",
    "Sapporo International Youth Hostel",
    "Sapporo Maruyama Guesthouse Tsumuri-An",
    "Sapporo Oriental Hotel",
    "SAPPORO STREAM HOTEL",
    "Sapporo Sun-Plaza",
    "Smile Hotel Premium Sapporo Susukino",
    "Smile Hotel Sapporo Susukino Minami",
    "SORARIA HOTEL SAPPORO",
    "Sotetsu FRESSA INN Sapporo Susukino",
    "SUPER HOTEL",
    "SUPER HOTEL SAPPORO SUSUKINO",
    "Susukino Granbell Hotel",
    "SwankyHotel",
    "Tabist THE GREEN SAPPORO",
    "TAKETO STAY PREMIERE SAPPORO EKI",
    "Ten to Ten NAKAJIMA-KOEN",
    "Ten to Ten SAPPORO STATION",
    "the b Sapporo",
    "The B Sapporo Susukino",
    "THE GATE HOTEL SAPPORO",
    "The Royal Park Camvas Sapporo Odori Park",
    "The Stay Sapporo",
    "THE STAY SAPPORO ANNEX",
    "Tiara Hotel Sapporo Susukino",
    "Time Peace Apartment",
    "Tmark City Hotel sapporo",
    "Tmark City Hotel Sapporo Odori",
  ],
};
